#!/bin/bash

replace_with_link() {
    if [ -e ~/$1 ]; then
        if [ ! -h ~/$1 ]; then
            mv -f ~/$1 ~/$1.bak
            ln -s ~/.home/$1 ~/$1
            echo "linked $1"
        else
            echo "symlink already exists for $1"
        fi
    else
        ln -s ~/.home/$1 ~/$1
        echo "linked $1"
    fi
}

files=(
    .zshrc
    .config/Code/User/settings.json
    .zshrc.d
    .docker/daemon.json
    .gitconfig
    .gitignore_global
)

for file in "${files[@]}"; do
    replace_with_link $file
done
